Slide Menu Controller Refactor
Kiswe/SlideMenuController pull request #1
Opened 2023-03-06 19:26 UTC by donileo

Please also review the initial commit already committed to make sure it is ok.

2023-03-07 16:06 UTC, timurbeg requested changes

2023-03-07 16:06 UTC, timurbeg commented on Sources/SlideMenuController/SlideMenuController.swift
> +        // Please to override it if necessary
these comments can be in one line

2023-03-08 15:22 UTC, donileo commented on Sources/SlideMenuController/SlideMenuController.swift
> +                return
We can but I like to leave it for breakpoint purposes sometimes, not all the times. So it's a preference choice here since these methods will usually need debugging.

2023-03-08 15:23 UTC, donileo commented on Sources/SlideMenuController/SlideMenuController.swift
> +        let tuple = view.bounds.divided(atDistance: bezelWidth, from: CGRectEdge.minXEdge)
Either way is fine, I'll keep as is.

2023-03-08 15:34 UTC, merged